### ISSUE TITLE
get the error when I try docker build -t muse . 

### ISSUE THREAD

**Issue by ricardo-kcc** [RiS3-Lab/muse#1]
![image](https://user-images.githubusercontent.com/64991294/143014397-15ea2c7e-6b6b-42bd-9924-cbfdf8b31e54.png)
![image](https://user-images.githubusercontent.com/64991294/143014432-fb61f057-05cf-4c09-8a14-cc75f592625f.png)
![image](https://user-images.githubusercontent.com/64991294/143014476-02a54ac8-b71f-498a-9fd4-f877b7d416a8.png)

the pip fail because python dependency?

**Comment by ricardo-kcc** [comment]
![image](https://user-images.githubusercontent.com/64991294/145772665-efa2119e-b491-428d-8f5e-91319991d942.png)
Now，the error happened when execute the same command.

**Comment by TotalKnob** [comment]
Don't blindly install/upgrade pip for Python2.7 as pip 21 dropped support for Python2.7.

Replace the pip upgrade by
```RUN           curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python -```
and add curl to the dependencies to install.
